In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'c:\\Users\\bruno\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

# Creating Arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.full(5, 4)

array([4, 4, 4, 4, 4])

In [6]:
a=np.array([1,2,3,4,5,12])
a

array([ 1,  2,  3,  4,  5, 12])

In [7]:
a[2]

3

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Multi-Dimensional Arrays

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
n=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [12]:
n[0,1]

2

In [13]:
n[0,1]=22
n

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [14]:
n[1]

array([4, 5, 6])

In [15]:
n[2]=[1,1,1]
n

array([[ 1, 22,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [16]:
n[:,1]

array([22,  5,  1])

# Randomly Generated Arrays

In [17]:
np.random.rand(5,2)

array([[0.15460395, 0.48848456],
       [0.5684724 , 0.63918497],
       [0.9337346 , 0.16586935],
       [0.83885435, 0.01347919],
       [0.78789819, 0.48526415]])

In [18]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(42)
np.random.randint(0,100,size=(5,5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74],
       [87, 99, 23,  2, 21],
       [52,  1, 87, 29, 37],
       [ 1, 63, 59, 20, 32]])

# Element Wise Operations

In [21]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [22]:
a+1

array([1, 2, 3, 4, 5])

In [23]:
b=(a+12)**3

In [24]:
a+b

array([1728, 2198, 2746, 3378, 4100])

# Comparison Operations

In [25]:
a >= b

array([False, False, False, False, False])

In [26]:
a > 2

array([False, False, False,  True,  True])

In [27]:
(a-b)<0

array([ True,  True,  True,  True,  True])

In [29]:
b>a

array([ True,  True,  True,  True,  True])

In [31]:
a[a<b]

array([0, 1, 2, 3, 4])

# Summarizing Operations

In [32]:
a.min()

0

In [33]:
b.max()

4096

In [34]:
a.sum()

10

In [35]:
a.mean()

2.0

In [36]:
b.std()

839.3151970505479