In [1]:
import numpy as np

In [2]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result


In [3]:
u=np.array([1,2,3,4,5])
v=np.array([1,2,3,4,5])

In [4]:
vector_vector_multiplication(u,v)

55.0

In [5]:
u.dot(v)

55

In [6]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]
    
    n=u.shape[0]

    result=np.zeros(n)
    for i in range(n):
        result[i]=vector_vector_multiplication(u[i],v)
    
    return result


In [7]:
a=np.random.randn(5,5)
a

array([[ 0.06390764,  0.02104369,  0.28713722, -0.12803142, -0.14656712],
       [ 0.8046525 , -0.77349456,  1.16302274,  1.40547111, -0.69863856],
       [-0.0898844 ,  0.76492453, -1.24003906, -1.74850617, -1.65641447],
       [-1.16064703,  0.53346554,  0.96810258,  0.13134255, -0.40788455],
       [ 0.45310978,  0.6318755 ,  0.92088056,  1.16119725, -0.62905715]])

In [8]:
b=np.array([1,2,3,5,9])

In [9]:
matrix_vector_multiplication(a,b)

array([ -0.99185446,   3.48634006, -25.93041358,  -0.20365646,
         4.62397431])

In [10]:
a.dot(b)

array([ -0.99185446,   3.48634006, -25.93041358,  -0.20365646,
         4.62397431])

In [11]:
def matrix_matrix_multiplication(u,v):
    assert u.shape[1] == v.shape[0]
    n_rows = u.shape[0]
    n_cols = v.shape[1]
    result = np.zeros((n_rows,n_cols))
    for i in range(n_cols):
        vi=v[:,i]
        Uvi=matrix_vector_multiplication(u,vi)
        result[:,i]=Uvi
    return result

In [12]:
#Matrix Inversion
a_i=np.linalg.inv(a)
a_i

array([[ 1.66058649, -0.17419714, -0.04760277, -0.72922633,  0.40473831],
       [ 0.38417745, -0.70181398, -0.03221636, -0.12803229,  0.85777988],
       [ 2.42310801, -0.06628818, -0.21649708,  0.10782588,  0.00920728],
       [-2.36286676,  0.22831253, -0.02424639,  0.13639198,  0.27237673],
       [ 0.767528  , -0.50602254, -0.42833756, -0.24425015,  0.07974298]])

In [13]:
a_i.dot(a)

array([[ 1.00000000e+00, -8.98900297e-17, -2.73902511e-17,
         9.44495511e-17,  3.97163389e-17],
       [-4.34651463e-17,  1.00000000e+00,  1.01975403e-16,
        -1.14756284e-16,  1.71145764e-17],
       [ 1.52897844e-16, -9.53856168e-17,  1.00000000e+00,
         1.20911029e-16, -9.61756592e-17],
       [-1.50816066e-16,  8.49751063e-17, -1.31047767e-16,
         1.00000000e+00,  3.41078501e-17],
       [-2.40666874e-18, -7.29750866e-17, -1.26654707e-16,
         9.07969226e-17,  1.00000000e+00]])

In [14]:
matrix_matrix_multiplication(a,a_i)

array([[ 1.00000000e+00,  2.77555756e-17, -1.38777878e-17,
        -3.46944695e-17,  0.00000000e+00],
       [ 6.66133815e-16,  1.00000000e+00,  0.00000000e+00,
        -2.77555756e-17, -6.93889390e-17],
       [ 6.66133815e-16, -1.11022302e-16,  1.00000000e+00,
         0.00000000e+00,  2.22044605e-16],
       [ 1.11022302e-16,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  2.77555756e-17],
       [ 3.33066907e-16, -5.55111512e-17, -5.55111512e-17,
        -2.77555756e-17,  1.00000000e+00]])